# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: 
         rules:
            - priorities: [json, xml]
            - fallback_format: json
    access_denied_listener:
        json: true
    allowed_methods_listener: true
    routing_loader:
        default_format: json
    view:
        default_engine: json
        view_response_listener: true