jms_serializer:
    visitors:
      json:
        options:
            - JSON_PRETTY_PRINT
            - JSON_UNESCAPED_SLASHES
            - JSON_PRESERVE_ZERO_FRACTION
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"